image: node:14-alpine

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - npm install
    - npm build

unit-test:
  stage: test
  tags:
    - docker
  script:
    - npm install
    - npm test
